application: gp-proto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /node_modules
  static_dir: node_modules
- url: /build
  static_dir: build
- url: /.*
  script: main.app
